validateGenericComponents
verrazzano/verrazzano-admission-controllers pull request #31
Opened 2020-10-06 14:36 UTC by shihchang

add validation for genericComponents

2020-10-06 16:16 UTC, bobdonat commented on pkg/model.go
> +					message := getSecret(clientsets, secName, "genericComponents.Deployment.Containers.Env", ev.Name)
same comment last arg should be gc.Name

2020-10-06 16:16 UTC, bobdonat commented on pkg/model.go
> +		for _, container := range gc.Deployment.Containers {
should you check InitContainers too

2020-10-06 16:16 UTC, bobdonat commented on pkg/model.go
> +		for _, container := range gc.Deployment.Containers {
should you check InitContainers too

2020-10-06 20:51 UTC, shihchang commented on pkg/model.go
> +			message := getSecret(clientsets, sec.Name, "genericComponents.Deployment.Template.Spec.ImagePullSecrets", sec.Name)
fixed

2020-10-06 20:52 UTC, shihchang commented on pkg/model.go
> +					message := getSecret(clientsets, secName, "genericComponents.Deployment.Containers.Env", ev.Name)
fixed

2020-10-06 20:52 UTC, shihchang commented on pkg/model.go
> +		for _, container := range gc.Deployment.Containers {
fixed

2020-10-06 20:52 UTC, shihchang commented on pkg/model.go
> +		for _, container := range gc.Deployment.Containers {
fixed

2020-10-06 21:15 UTC, pfmackin commented on go.mod
> +	github.com/stretchr/testify v1.5.1
can you make sure that testify and gopkg.in/yaml are the same versions as other verrazzano repos use

2020-10-06 21:24 UTC, pfmackin commented on pkg/binding_test.go
> +			want:    []string{"local", "cluster"},
Do you think it makes sense to test for more of the message text than just a few words?

2020-10-07 00:24 UTC, pfmackin commented on pkg/binding_test.go
> +func TestValidateBinding(t *testing.T) {
Needs a function header in the format of // WHEN ...

2020-10-07 00:25 UTC, pfmackin commented on pkg/model_test.go
> +func TestValidateGenericComponents(t *testing.T) {
Needs a function header in the format of // WHEN ...

2020-10-07 00:25 UTC, pfmackin commented on pkg/model_test.go
> +func TestValidateModel(t *testing.T) {
Needs a function header in the format of // WHEN ...

2020-10-07 13:39 UTC, bobdonat commented on pkg/serverhandler.go
> +	//v8oclientset "github.com/verrazzano/verrazzano-crd-generator/pkg/client/clientset/versioned"
this commented out line can be removed

2020-10-07 13:40 UTC, shihchang commented on go.mod
> +	github.com/stretchr/testify v1.5.1
same as verrazzano-operator

2020-10-07 13:41 UTC, shihchang commented on pkg/binding_test.go
> +			want:    []string{"local", "cluster"},
Those are substrings required to appear in the result message. fixed.

2020-10-07 13:41 UTC, shihchang commented on pkg/binding_test.go
> +func TestValidateBinding(t *testing.T) {
added

2020-10-07 13:41 UTC, shihchang commented on pkg/model_test.go
> +func TestValidateGenericComponents(t *testing.T) {
added

2020-10-07 13:41 UTC, shihchang commented on pkg/model_test.go
> +func TestValidateModel(t *testing.T) {
added

2020-10-07 13:43 UTC, shihchang commented on pkg/serverhandler.go
> +	//v8oclientset "github.com/verrazzano/verrazzano-crd-generator/pkg/client/clientset/versioned"
removed

2020-10-07 13:47 UTC, bobdonat commented on test/integ/integ_test.go
> +var _ = Describe("Apply model with GenericComponents", func() {
this could be simplified if the model/binding only had generic components.

2020-10-07 13:50 UTC, bobdonat commented on test/integ/integ_test.go
> +var _ = Describe("Apply model with GenericComponents", func() {
should there also be a test for init container env secret ref missing and tests for container and init container ports

2020-10-07 18:36 UTC, shihchang commented on test/integ/integ_test.go
> +var _ = Describe("Apply model with GenericComponents", func() {
simplified

2020-10-07 18:36 UTC, shihchang commented on test/integ/integ_test.go
> +var _ = Describe("Apply model with GenericComponents", func() {
added  test for init container env secret ref missing

2020-10-07 19:09 UTC, shihchang commented on test/integ/integ_test.go
> +var _ = Describe("Apply model with GenericComponents", func() {
added test for invalid  init container ports. 
I plan to add more validation coverage in unit-test which runs more efficiently than integ-test.

2020-10-08 13:04 UTC, bobdonat commented on THIRD_PARTY_LICENSES.txt
> -======== Creative Commons License
All references to Creative Commons License have been removed in the updated THIRD_PARTY_LICENSES.txt.  My understanding is these references need to stay,

2020-10-08 13:47 UTC, markxnelson commented on THIRD_PARTY_LICENSES.txt
> -======== Creative Commons License
that's right, these need to be fixed

2020-10-08 13:47 UTC, markxnelson requested changes
fix cc licenses in tpl file

2020-10-08 13:59 UTC, shihchang commented on THIRD_PARTY_LICENSES.txt
> -======== Creative Commons License
added it back and it failed "Third Party License Check" https://build.verrazzano.io/job/verrazzano-admission-controllers/job/scchen%252Fgc/
I ran again "attribution-helper gen" and it removed Creative Commons License. 
How should I fix it?

2020-10-08 15:23 UTC, shihchang commented on THIRD_PARTY_LICENSES.txt
> -======== Creative Commons License
fixed as Bob suggested

2020-10-08 18:26 UTC, markxnelson commented on pkg/binding_test.go
> +		k8sCli  kubernetes.Interface
what does cli mean? command line interface? client? something else? neither seem to fit the type. confusing

2020-10-08 18:26 UTC, markxnelson commented on pkg/binding_test.go
> +		want    []string
what is want? is it the expected value(s)? expected is the more commonly used name, and its clearer

2020-10-08 18:26 UTC, markxnelson commented on pkg/binding_test.go
> +			rev := validateBinding(review, *tt.binding, clientsets, "myVerrazzanoURI")
what is rev?

2020-10-08 18:26 UTC, markxnelson commented on pkg/binding_test.go
> +			if len(tt.want) == 0 {
where is want getting set/updated? this is quite difficult to understand. is this checking that there were no expected output strings provided in the test?

2020-10-08 18:26 UTC, markxnelson commented on pkg/model.go
> +	if response != "" {
wouldn't it be better for valideGenericComponents to return an error, not just an empty string, if something went wrong?

2020-10-08 18:26 UTC, markxnelson commented on pkg/model.go
> +	return ""
i do not like this as all, if the return value is a list of errors, then use the error type, not string

2020-10-08 18:26 UTC, markxnelson commented on pkg/serverhandler.go
> +	V8oClient v8oclientset.VerrazzanoV1beta1Interface
i don't understand the changes in this file - why are we changing these?

2020-10-08 18:26 UTC, markxnelson commented on pkg/utils_test.go
> +func (f *FakeVzClient) VerrazzanoModels(namespace string) vzcli.VerrazzanoModelInterface {
feels like all the FakeVzClient defs could be in their own file instead of just chucked in here with everything else

2020-10-08 18:26 UTC, markxnelson commented on pkg/utils_test.go
> +	panic("implement me")
do we need to implement these? if yes, implement them.. if no, change the error message....

2020-10-08 18:26 UTC, markxnelson commented on pkg/utils_test.go
> +	_, err := vzcli.VerrazzanoModels(model.Namespace).List(context.TODO(), metav1.ListOptions{})
why do we expect an error here? shouldn't list work?

2020-10-08 19:15 UTC, markxnelson commented on pkg/binding_test.go
> +		k8sCli  kubernetes.Interface
chen will change

2020-10-08 19:16 UTC, markxnelson commented on pkg/binding_test.go
> +			if len(tt.want) == 0 {
discussed - this is actually checking for the case where there were no expected messages and none were received - chen will add a comment to make it clear

2020-10-08 19:17 UTC, markxnelson commented on pkg/model.go
> +	return ""
agreed to address in separate pr since it is all through the code and preexisting

2020-10-08 20:13 UTC, shihchang commented on pkg/binding_test.go
> +		k8sCli  kubernetes.Interface
renamed to k8sClient

2020-10-08 20:15 UTC, shihchang commented on pkg/binding_test.go
> +		want    []string
renamed to expectedErrorMessages

2020-10-08 20:17 UTC, shihchang commented on pkg/binding_test.go
> +			rev := validateBinding(review, *tt.binding, clientsets, "myVerrazzanoURI")
renamed to admissionReview

2020-10-08 20:28 UTC, shihchang commented on pkg/binding_test.go
> +			if len(tt.want) == 0 {
//empty array if the validation result is positive

2020-10-08 20:29 UTC, shihchang commented on pkg/model.go
> +	return ""
filed VZ-1440

2020-10-08 20:30 UTC, shihchang commented on pkg/model.go
> +	if response != "" {
revisit this in VZ-1440

2020-10-08 20:31 UTC, shihchang commented on pkg/serverhandler.go
> +	V8oClient v8oclientset.VerrazzanoV1beta1Interface
Changed to use interface so it can be mocked to test

2020-10-08 20:32 UTC, shihchang commented on pkg/utils_test.go
> +func (f *FakeVzClient) VerrazzanoModels(namespace string) vzcli.VerrazzanoModelInterface {
This is to avoid unnecessary coverage of  test-util codes

2020-10-08 20:33 UTC, shihchang commented on pkg/utils_test.go
> +	panic("implement me")
This was generated implementation code, changed to "implement this if need"

2020-10-08 20:34 UTC, shihchang commented on pkg/utils_test.go
> +	_, err := vzcli.VerrazzanoModels(model.Namespace).List(context.TODO(), metav1.ListOptions{})
vzClient = MockError(vzClient ...) was to mock vzClient to return an error when List is called

2020-10-09 13:46 UTC, bobdonat approved these changes
Looks OK to me.

2020-10-09 19:00 UTC, markxnelson approved these changes
looks much better, thanks a lot

2020-10-09 20:34 UTC, merged